version: "3.9"
services:
  redis:
    image: redis:7-alpine
  gateway:
    build:
      context: ./apps/collab_gateway
      network: host
    ports:
      - "1234:1234"
    depends_on:
      - redis
    environment:
      PORT: 1234
      API_TOKEN: changeme
      ALLOWED_ORIGINS: localhost:5173
      COLLATEX_ALLOWED_ORIGINS: http://localhost:5173
      REDIS_URL: redis://redis:6379/0
  frontend:
    build:
      context: ./apps/frontend
      network: host
      args:
        VITE_API_TOKEN: changeme
    ports: ["5173:80"]
