version: '3'
services:
  compile-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/backend/compile-service
    command: uvicorn compile_service.app.main:app --host 0.0.0.0 --port 8000
