version: "3.9"
services:
  backend:
    build: ./backend/compile-service
    ports:
      - "8080:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  worker:
    build: ./backend/compile-service
    command: celery -A collatex.tasks worker -Q compile -l info
    volumes:
      - ./storage:/app/storage
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  gateway:
    build: ./gateway
    ports:
      - "1234:1234"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_ORIGIN=http://localhost:8080
    depends_on:
      - backend
  redis:
    image: redis:7-alpine

