version: "3.9"
services:
  redis:
    image: redis:7-alpine
  gateway:
    build: ./apps/collab_gateway
    ports:
      - "1234:1234"
    depends_on:
      - redis
    environment:
      PORT: 1234
      ALLOWED_ORIGINS: localhost
      COLLATEX_API_TOKEN: changeme
  frontend:
    build:
      context: ./apps/frontend
      args:
        VITE_API_TOKEN: changeme
    ports: ["5173:80"]
