version: "3.9"
services:
  redis:
    image: redis:7-alpine
  backend:
    build: ./backend/compile-service
    environment:
      COLLATEX_STATE: redis
      REDIS_URL: redis://redis:6379
      COLLATEX_API_TOKEN: changeme
    ports: ["8080:8080"]
  worker:
    build: ./backend/compile-service
    entrypoint: ["uv", "run", "compile_service.worker:main"]
    environment:
      COLLATEX_STATE: redis
      REDIS_URL: redis://redis:6379
      COLLATEX_API_TOKEN: changeme
  gateway:
    build: ./apps/collab_gateway
    environment:
      PORT: 1234
      ALLOWED_ORIGINS: localhost
      COLLATEX_API_TOKEN: changeme
    ports: ["1234:1234"]
  frontend:
    build:
      context: ./apps/frontend
      args:
        VITE_API_TOKEN: changeme
    ports: ["5173:80"]

