version: "3.9"
services:
  redis:
    image: redis:7-alpine
  compile-service:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8080:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      COLLATEX_STATE: redis
      REDIS_URL: redis://redis:6379/0
      COLLATEX_API_TOKEN: changeme
      COLLATEX_ALLOWED_ORIGINS: http://localhost:5173
      COLLATEX_RATE_LIMIT: 20
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A collatex.tasks worker -Q compile -l info
    volumes:
      - ./storage:/app/storage
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  gateway:
    build: ./apps/collab_gateway
    ports:
      - "1234:1234"
    depends_on:
      - redis
    environment:
      PORT: 1234
      ALLOWED_ORIGINS: localhost
      COLLATEX_API_TOKEN: changeme
  frontend:
    build:
      context: ./apps/frontend
      args:
        VITE_API_TOKEN: changeme
    ports: ["5173:80"]

