name: CollaTeX CI
on: [push, pull_request]
jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        state: [memory, redis]
    env:
      COLLATEX_STATE: ${{ matrix.state }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: pip install uv
      - name: Install deps
        run: uv pip install -e backend/compile-service[dev]
      - name: Start Redis (if needed)
        if: matrix.state == 'redis'
        run: docker run -d -p 6379:6379 redis:7-alpine
      - name: Lint
        run: make lint
      - name: Type-check
        run: make typecheck
      - name: Tests
        run: make test
  gateway:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Lint and Test
        run: |
          npm run lint --workspace apps/collab_gateway
          npm test --workspace apps/collab_gateway

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Lint and Test
        run: |
          npm run lint --workspace apps/frontend
          npm run test --workspace apps/frontend
