name: CollaTeX CI
on: [push, pull_request]
jobs:
  gateway:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Lint and Test
        run: |
          npm run lint --workspace apps/collab_gateway
          npm test --workspace apps/collab_gateway
      - name: Smoke build
        run: docker compose build gateway

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Fetch BusyTeX assets
        run: npm run fetch:busytex --workspace apps/frontend
      - name: Lint and Test
        run: |
          npm run lint --workspace apps/frontend
          npm run test --workspace apps/frontend
