name: CollaTeX CI
on: [push, pull_request]
jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        state: [memory, redis]
    env:
      COLLATEX_STATE: ${{ matrix.state }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: pip install uv
      - name: Install deps
        run: uv pip install -e backend/compile-service[dev]
      - name: Start Redis (if needed)
        if: matrix.state == 'redis'
        run: docker run -d -p 6379:6379 redis:7-alpine
      - name: Lint
        run: make lint
      - name: Type-check
        run: make typecheck
      - name: Tests
        run: make test
